version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Install geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz &&
            tar -xvzf geckodriver* &&
            chmod +x geckodriver &&
            sudo mv geckodriver /usr/local/bin
      - run:
          name: Install Latest Browsers
          command: |
            sudo apt-get install unzip
            wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
            chmod +x ~/Downloads/chromedriver
            sudo mv -f ~/Downloads/chromedriver /usr/local/share/chromedriver
            sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
            sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
            
      - run:
          name: Run rspec
          command: bundle exec rspec blog-test.rb
      


  
