version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
      name: Install and start geckodriver
      command: |
        wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz &&
        tar -xvzf geckodriver* &&
        chmod +x geckodriver &&
        sudo mv geckodriver /usr/local/bin

       - run:
            name: Install the latest firefox
            command: |
              sudo apt-get remove firefox-mozilla-build binutils &&
              sudo sh -c "echo 'deb http://ftp.hr.debian.org/debian sid main' >> /etc/apt/sources.list" &&
              sudo apt-get update &&
              sudo apt-get install -t sid firefox &&
              firefox --version
      - run:
          name: Run rspec
          command: bundle exec rspec blog-test.rb
      


  
