version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      
      
dependencies: 
    override: 
      - sudo apt-get update && sudo apt-get install libpango1.0-0 && sudo apt-get install firefox 
     
      - run:
          name: Run rspec
          command: bundle exec rspec blog-test.rb
      


  
