version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Install geckodriver
          command: |
            wget https://github.com/mozilla/geckodriver/releases/download/v0.19.1/geckodriver-v0.19.1-linux64.tar.gz &&
            tar -xvzf geckodriver* &&
            chmod +x geckodriver &&
            sudo mv geckodriver /usr/local/bin
      - run:
          name: Install Latest Browsers
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get install gconf-service
            sudo apt-get install google-chrome-stable
      
      - run:
          name: Run rspec
          command: bundle exec rspec blog-test.rb
      


  
